name: Scrape USACO

on:
  schedule:
    - cron: '14 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Scrape USACO
        run: |
          cargo run --package usaco-standings-scraper --example scrape --release >/tmp/data.json

      - uses: actions/checkout@v4
        with:
          ref: data

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          cp /tmp/data.json .
          git add .

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update scraped USACO data"
            git push
          else
            echo "no changes to commit"
          fi
